In [4]:
"""
Q.1 - Create a numpy array with 10 elements of the shape(10,1)

      using np.random and find out the mean of the elements using basic numpy functions.
         
"""
# Sol

import numpy as np
array=np.random.rand(10,1)
print(array)
print("Mean",array.mean(axis=0))

[[0.80691087]
 [0.81832208]
 [0.46616752]
 [0.52963518]
 [0.63085761]
 [0.51567116]
 [0.77321439]
 [0.96712855]
 [0.20116286]
 [0.31063078]]
Mean [0.6019701]


In [11]:
"""Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random
         find the variance and standard deviation of the elements.

"""
# Sol

import numpy as np
array=np.random.rand(20,1)
print("array",array)
print("variance",array.var(axis=0))
print("standard deviation",array.std(axis=0))

array [[0.7660869 ]
 [0.90969695]
 [0.44590714]
 [0.2225718 ]
 [0.17609672]
 [0.81114705]
 [0.91447848]
 [0.91742107]
 [0.20351011]
 [0.44318267]
 [0.82706601]
 [0.3570787 ]
 [0.38587658]
 [0.57810759]
 [0.75089403]
 [0.41377346]
 [0.64675278]
 [0.96429543]
 [0.05686144]
 [0.63019619]]
variance [0.07619065]
standard deviation [0.27602654]


In [14]:
"""Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random.
         Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25).
         Using basic numpy math functions only find the sum of all the elements of the new matrix.
"""

# Sol

import numpy as np
A=np.random.rand(10,20)
B=np.random.rand(20,25)

C=A.dot(B)
print("Matrix \b \n",C)
print("Shape of new array: \n \b",np.shape(C))
print("Sum of elements in array: \n \b",np.sum(C))

Matrix  
 [[4.89534379 6.37418697 4.71310688 5.61438709 5.88245404 6.60054353
  5.60585976 4.9177272  5.93916918 5.27863471 6.00008794 6.08031974
  4.91311551 6.09294444 5.40000166 5.53255985 5.3859431  5.57179191
  4.75325743 5.93983591 4.16216097 4.99016056 5.59233026 5.43330759
  3.89685442]
 [4.50022637 5.6079346  5.04990178 5.18943818 5.00028769 5.89534211
  4.98835725 5.02716567 5.07878791 4.79190244 5.12011607 5.23795515
  4.55769019 5.62693263 4.94496511 5.54400452 4.81227752 4.84284413
  3.96130137 5.47414131 4.40974194 4.64490914 4.72344007 5.61623027
  4.54221796]
 [3.95296107 4.62496515 4.57063878 4.10060113 4.05744334 5.04785208
  4.72267646 3.82016296 5.18594345 4.31214351 4.32360597 5.15413699
  4.35091579 4.89241869 4.24487098 4.32091699 4.53842241 4.74481344
  4.08732692 4.72083951 3.46267181 5.19669292 4.22769696 4.35349497
  3.75525174]
 [3.85944597 4.52576703 3.92425064 3.91031287 4.35685453 5.00135006
  4.12098482 3.70069961 5.03990403 3.93517059 4.5592046  4.3484

In [22]:
"""Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) 
         such that each element is the following function applied on each element of A. 
                       f(x)=1 / (1 + exp(-x)) 
         Apply this function to each element of A and print the new array holding the value the function returns
         Example:

                a=[a1,a2,a3]   
                n(new array to be printed )=[ f(a1), f(a2), f(a3)]
"""
# Sol

import numpy as np
A=np.random.rand(10,1)
print("Array: \n",A)

a=lambda x:(1/(1+np.exp(-x)))
print("New Array: \n", np.array(list(map(a,A))))

Array: 
 [[0.17444633]
 [0.04617257]
 [0.1468885 ]
 [0.76006591]
 [0.99619857]
 [0.47901816]
 [0.17652411]
 [0.53413928]
 [0.62980843]
 [0.15820322]]
New Array: 
 [[0.54350132]
 [0.51154109]
 [0.53665624]
 [0.68136804]
 [0.73031052]
 [0.617516  ]
 [0.54401679]
 [0.63044801]
 [0.65244602]
 [0.53946852]]
